-- ─────────────────────────────────────────────────────────────────────────────
-- DealFlow360 — Legacy SQL Seed File (DEPRECATED)
-- ─────────────────────────────────────────────────────────────────────────────
--
-- ⚠️  This file is DEPRECATED and no longer used.
--
-- DealFlow360 uses Prisma ORM for schema management and seeding:
--
--   Schema:        prisma/schema.prisma
--   Migrations:    npx prisma db push  (or prisma migrate deploy in production)
--   Demo Seed:     npm run seed:demo   (runs prisma/seed.js via Prisma client)
--
-- To set up a fresh database:
--   1. Configure DATABASE_URL in backend/.env
--   2. cd backend
--   3. npx prisma db push          # Apply Prisma schema to PostgreSQL
--   4. npm run seed:demo           # Seed demo data via Prisma client
--
-- ─────────────────────────────────────────────────────────────────────────────
